name: PingSpot

services:
  pingspot-server:
    build: .
    container_name: pingspot_server
    restart: always
    ports:
      - "${HOST_PORT}:${PORT}"
    depends_on:
      pingspot-postgres:
          condition: service_healthy
      pingspot-redis:
          condition: service_healthy
      pingspot-mongodb:
          condition: service_healthy
    env_file:
      - .env
    networks:
      - pingspot_network

  pingspot-redis:
    image: redis:latest
    container_name: pingspot_redis
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"
    volumes:
      - pingspot_redis_data:/data
    networks:
      - pingspot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  pingspot-postgres:
    image: postgis/postgis:15-3.4
    container_name: pingspot_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "${POSTGRE_HOST_PORT}:${POSTGRE_PORT}"
    env_file:
      - .env
    volumes:
      - pingspot_postgre_data:/var/lib/postgresql/data
    networks:
      - pingspot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  pingspot-mongodb:
    image: mongo:latest
    container_name: pingspot_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_PORT}"
    volumes:
      - pingspot_mongodb_data:/data/db
    networks:
      - pingspot_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  pingspot_network:

volumes:
  pingspot_redis_data:
  pingspot_postgre_data:
  pingspot_mongodb_data:
