// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password/email-verification": {
            "post": {
                "description": "Mengirim email verifikasi untuk proses lupa kata sandi jika email terdaftar",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Send forgot password verification email",
                "parameters": [
                    {
                        "description": "Forgot password email verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordEmailVerificationRequest"
                        }
                    }
                ]
            }
        },
        "/auth/forgot-password/link-verification": {
            "post": {
                "description": "Memverifikasi link lupa kata sandi berdasarkan code dan email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify forgot password link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/auth/forgot-password/reset-password": {
            "post": {
                "description": "Mengatur ulang kata sandi pengguna menggunakan email dan kata sandi baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Forgot password reset request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordResetPasswordRequest"
                        }
                    }
                ]
            }
        },
        "/auth/google": {
            "get": {
                "description": "Memulai proses autentikasi OAuth Google",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Google OAuth login"
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Callback OAuth Google untuk autentikasi dan login pengguna",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Google OAuth callback"
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login pengguna dengan email dan password, lalu mengatur access_token dan refresh_token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ]
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logout user dengan menghapus access token dan refresh token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout user"
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Memperbarui access token dan refresh token menggunakan refresh_token cookie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh access token"
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registrasi pengguna baru dan kirim link verifikasi email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ]
            }
        },
        "/auth/verification": {
            "post": {
                "description": "Verifikasi akun pengguna menggunakan parameter code1, userId, dan code2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Verification code 1",
                        "name": "code1",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Verification code 2",
                        "name": "code2",
                        "in": "query",
                        "required": true
                    }
                ]
            }
        },
        "/user/security": {
            "post": {
                "description": "Mengubah kata sandi pengguna dengan verifikasi token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user password",
                "parameters": [
                    {
                        "description": "Update security request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SaveUserSecurityRequest"
                        }
                    }
                ]
            }
        },
        "/user/profile": {
            "post": {
                "description": "Memperbarui profil pengguna termasuk foto profil, nama, username, gender, ulang tahun, dan bio",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Update profile request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SaveUserProfileRequest"
                        }
                    }
                ]
            },
            "get": {
                "description": "Mengambil profil pengguna saat ini berdasarkan JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get current user profile"
            }
        },
        "/user/statistics": {
            "get": {
                "description": "Mengambil statistik pengguna saat ini (laporan, reaksi, voting, dll)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user statistics"
            }
        },
        "/user/profile/{username}": {
            "get": {
                "description": "Mengambil profil pengguna berdasarkan username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user profile by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/report": {
            "post": {
                "description": "Membuat laporan baru dengan gambar dan lokasi geografis",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Create new report",
                "parameters": [
                    {
                        "description": "Create report request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReportRequest"
                        }
                    }
                ]
            },
            "get": {
                "description": "Mengambil daftar laporan dengan filter dan pagination. Jika reportID diberikan, akan mengambil detail laporan tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get reports list or detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID (optional, get specific report)",
                        "name": "reportID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cursor ID for pagination",
                        "name": "cursorID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Distance filter as JSON {distance: number, lat: number, lng: number}",
                        "name": "distance",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Report type filter",
                        "name": "reportType",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Report status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by field",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Has progress filter (true/false)",
                        "name": "hasProgress",
                        "in": "query"
                    }
                ]
            }
        },
        "/report/{reportID}": {
            "post": {
                "description": "Mengubah laporan yang sudah dibuat termasuk gambar dan lokasi",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Edit existing report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edit report request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EditReportRequest"
                        }
                    }
                ]
            },
            "delete": {
                "description": "Menghapus laporan (soft delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Delete report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/report/{reportID}/reaction": {
            "post": {
                "description": "Memberikan reaksi pada laporan (emoji reaction)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "React to report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reaction request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReactionReportRequest"
                        }
                    }
                ]
            }
        },
        "/report/{reportID}/vote": {
            "post": {
                "description": "Melakukan voting pada laporan (upvote/downvote)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Vote on report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VoteReportRequest"
                        }
                    }
                ]
            }
        },
        "/report/{reportID}/progress": {
            "post": {
                "description": "Mengunggah progress/update terbaru untuk suatu laporan",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Upload report progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Upload progress request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UploadProgressReportRequest"
                        }
                    }
                ]
            },
            "get": {
                "description": "Mengambil daftar progress/update dari suatu laporan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get report progress list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/report/{reportID}/comment": {
            "post": {
                "description": "Membuat komentar pada laporan dengan optional media attachment",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Create report comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create comment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReportCommentRequest"
                        }
                    }
                ]
            }
        },
        "/report/{reportID}/comments": {
            "get": {
                "description": "Mengambil daftar komentar dari suatu laporan dengan pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get report comments list",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report ID",
                        "name": "reportID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor ID for pagination",
                        "name": "cursorID",
                        "in": "query"
                    }
                ]
            }
        },
        "/report/statistics": {
            "get": {
                "description": "Mengambil statistik laporan secara umum",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get report statistics"
            }
        },
        "/report/comments/{commentID}/replies": {
            "get": {
                "description": "Mengambil daftar balasan untuk suatu komentar laporan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "report"
                ],
                "summary": "Get report comment replies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor ID for pagination",
                        "name": "cursorID",
                        "in": "query"
                    }
                ]
            }
        },
        "/search": {
            "get": {
                "description": "Melakukan pencarian data pengguna dan laporan berdasarkan query dengan pagination support",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search users and reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (minimum 3 characters)",
                        "name": "searchQuery",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Cursor ID for users data pagination",
                        "name": "usersDataCursorID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cursor ID for reports data pagination",
                        "name": "reportsDataCursorID",
                        "in": "query"
                    }
                ]
            }
        }
    },
    "definitions": {
        "dto.ForgotPasswordEmailVerificationRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ForgotPasswordResetPasswordRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "passwordConfirmation"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "passwordConfirmation": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password",
                "provider",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "EMAIL",
                        "GOOGLE",
                        "GITHUB"
                    ]
                },
                "providerId": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "dto.SaveUserSecurityRequest": {
            "type": "object",
            "required": [
                "currentPassword",
                "currentPasswordConfirmation",
                "newPassword",
                "newPasswordConfirmation"
            ],
            "properties": {
                "currentPassword": {
                    "type": "string",
                    "minLength": 6
                },
                "currentPasswordConfirmation": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string",
                    "minLength": 6
                },
                "newPasswordConfirmation": {
                    "type": "string"
                }
            }
        },
        "dto.SaveUserProfileRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 3
                },
                "gender": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                }
            }
        },
        "dto.ReactionReportRequest": {
            "type": "object",
            "required": [
                "reactionType"
            ],
            "properties": {
                "reactionType": {
                    "type": "string",
                    "enum": [
                        "LIKE",
                        "DISLIKE"
                    ]
                }
            }
        },
        "dto.VoteReportRequest": {
            "type": "object",
            "required": [
                "voteType"
            ],
            "properties": {
                "voteType": {
                    "type": "string",
                    "enum": [
                        "RESOLVED",
                        "ON_PROGRESS",
                        "NOT_RESOLVED"
                    ]
                }
            }
        },
        "dto.CreateReportRequest": {
            "type": "object",
            "required": [
                "reportTitle",
                "reportType",
                "reportDescription",
                "detailLocation",
                "latitude",
                "longitude"
            ],
            "properties": {
                "reportTitle": {
                    "type": "string"
                },
                "reportType": {
                    "type": "string",
                    "enum": [
                        "INFRASTRUCTURE",
                        "ENVIRONMENT",
                        "SAFETY",
                        "TRAFFIC",
                        "PUBLIC_FACILITY",
                        "WASTE",
                        "WATER",
                        "ELECTRICITY",
                        "HEALTH",
                        "SOCIAL",
                        "EDUCATION",
                        "ADMINISTRATIVE",
                        "DISASTER",
                        "OTHER"
                    ]
                },
                "reportDescription": {
                    "type": "string"
                },
                "detailLocation": {
                    "type": "string"
                },
                "hasProgress": {
                    "type": "boolean"
                },
                "mapZoom": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 21
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "displayName": {
                    "type": "string"
                },
                "addressType": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "countryCode": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "postCode": {
                    "type": "string"
                },
                "county": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "road": {
                    "type": "string"
                },
                "village": {
                    "type": "string"
                },
                "suburb": {
                    "type": "string"
                },
                "image1Url": {
                    "type": "string"
                },
                "image2Url": {
                    "type": "string"
                },
                "image3Url": {
                    "type": "string"
                },
                "image4Url": {
                    "type": "string"
                },
                "image5Url": {
                    "type": "string"
                }
            }
        },
        "dto.EditReportRequest": {
            "type": "object",
            "required": [
                "reportTitle",
                "reportType",
                "reportDescription",
                "detailLocation",
                "latitude",
                "longitude"
            ],
            "properties": {
                "reportTitle": {
                    "type": "string"
                },
                "reportType": {
                    "type": "string",
                    "enum": [
                        "INFRASTRUCTURE",
                        "ENVIRONMENT",
                        "SAFETY",
                        "TRAFFIC",
                        "PUBLIC_FACILITY",
                        "WASTE",
                        "WATER",
                        "ELECTRICITY",
                        "HEALTH",
                        "SOCIAL",
                        "EDUCATION",
                        "ADMINISTRATIVE",
                        "DISASTER",
                        "OTHER"
                    ]
                },
                "reportDescription": {
                    "type": "string"
                },
                "detailLocation": {
                    "type": "string"
                },
                "hasProgress": {
                    "type": "boolean"
                },
                "mapZoom": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 21
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "displayName": {
                    "type": "string"
                },
                "addressType": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "countryCode": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "postCode": {
                    "type": "string"
                },
                "county": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "road": {
                    "type": "string"
                },
                "village": {
                    "type": "string"
                },
                "suburb": {
                    "type": "string"
                },
                "image1Url": {
                    "type": "string"
                },
                "image2Url": {
                    "type": "string"
                },
                "image3Url": {
                    "type": "string"
                },
                "image4Url": {
                    "type": "string"
                },
                "image5Url": {
                    "type": "string"
                }
            }
        },
        "dto.UploadProgressReportRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "enum": [
                        "RESOLVED",
                        "NOT_RESOLVED",
                        "ON_PROGRESS"
                    ]
                },
                "notes": {
                    "type": "string"
                },
                "attachment1": {
                    "type": "string"
                },
                "attachment2": {
                    "type": "string"
                }
            }
        },
        "dto.CreateReportCommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "mediaURL": {
                    "type": "string"
                },
                "mediaType": {
                    "type": "string",
                    "enum": [
                        "IMAGE",
                        "GIF",
                        "VIDEO"
                    ]
                },
                "mediaWidth": {
                    "type": "integer",
                    "minimum": 1
                },
                "mediaHeight": {
                    "type": "integer",
                    "minimum": 1
                },
                "mentions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "threadRootID": {
                    "type": "string",
                    "minLength": 24,
                    "maxLength": 24
                },
                "parentCommentID": {
                    "type": "string",
                    "minLength": 24,
                    "maxLength": 24
                }
            }
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/pingspot/api",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
